<br /><br />
<div id="view-content">
	<p>View script for controller <b>Guestbook</b> and script/action name <b>index</b></p>
</div>

<!-- application/views/scripts/guestbook/index.phtml -->

 

<p><a href="<?php echo $this->url(

    array(

        'controller' => 'guestbook',

        'action'     => 'sign'

    ),

    'default',

    true) ?>">Sign Our Guestbook</a></p>

 

Guestbook Entries: <br />

<ul>

<?php
foreach ($this->paginator as $item) echo '<li>' . $item->id . '</li>';
?>

</ul>

<?php echo $this->paginator; ?>

<?php echo $this->loginForm?>